### ISSUE TITLE
Неправильно определяется текущий сервис

### ISSUE THREAD

**Issue by MadridianFox** [ensi-platform/elc#16]
Если в воркспейсе зарегистрированы два сервиса и название первого полностью вхолдит в название второго,
то автоопределение сервиса по текущей папке может выдавать неверный результат.
Например
- customers
- customers-api
когда мы находимся в папке /path/to/apps/customers, elc start может запустить сервис customers-api

**Comment by MadridianFox** [comment]
workaround: можно через env.yaml задать другой пути, так чтобы путь до одного сервисе не был подстрокой в пути до другого
```
components:
  customers-customers:
    path: ${APPS_ROOT}/customers-main
  customers-customers-api:
    path: ${APPS_ROOT}/customers-api
```
